# Generated by Django 3.2.4 on 2021-06-25 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_newtopic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtopic',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 17, 22, 35, 463343, tzinfo=utc), verbose_name='vaxti'),
        ),
    ]
